[tox]
envlist = py3, fmt, style, lint

[testenv]
usedevelop = True
deps =
    -rrequirements.txt
    pytest
commands = pytest tests

[testenv:fmt]
allowlist_externals =
    bash
deps =
    black
    autoflake
    pyupgrade
    isort
commands =
    bash -c 'find SaiyanQuest/ -iname "*.py" -type f | parallel pyupgrade --exit-zero-even-if-changed --py39-plus --keep-runtime-typing'
    autoflake -r -i --imports=SaiyanQuest,pygame --ignore-init-module-imports SaiyanQuest/
    isort SaiyanQuest tests
    black SaiyanQuest tests

[testenv:style]
deps =
    black
    autoflake
    isort
commands =
    autoflake -r -i --imports=SaiyanQuest,pygame --ignore-init-module-imports --check-diff --quiet SaiyanQuest/
    isort --check --diff --quiet SaiyanQuest tests
    black --check --diff --quiet SaiyanQuest tests

[testenv:lint]
deps =
    flake8
commands =
    flake8 SaiyanQuest tests